version: "3"

services:
  # https://hub.docker.com/r/flexpool/flexfarmer
  # https://www.flexpool.io/get-started/xch/flexfarmer
  flexfarmer:
    container_name: flexfarmer
    image: flexpool/flexfarmer:latest
    restart: always
    environment:
      - TZ=Europe/Sofia
    volumes:
      - /mnt:/mnt/
      - ${HOME}/flexfarmer/:/config/
    entrypoint:
      ["bash", "-c", "/flexfarmer -c /config/config.yml"]
